; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{444538EE-4F35-4245-AEAE-6C149BB852C9}
AppName=LisTube
AppVersion=1.9.33
AppVerName=LisTube 1.9.33
AppPublisher=LisTube
AppPublisherURL=https://github.com/amplimusic/LisTube
AppSupportURL=https://github.com/amplimusic/LisTube
AppUpdatesURL=https://github.com/amplimusic/LisTube
DefaultDirName={commonpf}\LisTube
DefaultGroupName=LisTube
AllowNoIcons=yes
OutputDir=output
OutputBaseFilename=LisTube
SetupIconFile=..\LisTube\finalIcon.ico
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon=..\LisTube\finalIcon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "chinese"; MessagesFile: "ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
Source: "..\LisTube\bin\Release\net8.0-windows\*"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\bin\bin32\ffmpeg.exe"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\LisTube"; Filename: "{app}\LisTube.exe"
Name: "{commondesktop}\LisTube"; Filename: "{app}\LisTube.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\LisTube.exe"; Description: "{cm:LaunchProgram,LisTube}"; Flags: nowait postinstall skipifsilent

